name: Build & Release

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.0.0, v1.0.1, etc.

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish
        env:
          # GITHUB_TOKEN is automatically provided by GitHub Actions
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist